export const GET_USER_PRODUCT_DETAILS = "GET_USER_PRODUCT_DETAILS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_COLORS = "GET_COLORS";
export const FETCH_DRAFT_DICTIONARY_LIST = "FETCH_DRAFT_DICTIONARY_LIST";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGOUT_USER = "LOGOUT_USER";
